name: A workflow for my first GitHub Action
on: pull_request
jobs:
  build:
    name: My first Hello World action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo "hello world"
     

